import os
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI

from workflow_engine import state
from workflow_engine.state import DataScienceState
from workflow_engine.tools.python_repl import DataScienceREPL
import time

llm = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite", temperature=0)

def modelling_agent_node(state: DataScienceState) -> dict:
    """
    Trains machine learning models on the engineered dataset, evaluates them, 
    and saves the best model and its evaluation metrics.
    """
    print("--- AGENT: MODELLING ---")
    
    # 1. Resolve paths
    current_dir = os.getcwd()
    if current_dir.endswith('notebooks'):
        project_root = os.path.dirname(current_dir)
    else:
        project_root = current_dir

    input_path = os.path.abspath(os.path.join(project_root, state["current_dataset_path"])).replace('\\', '/')
    artifacts_dir = os.path.join(project_root, "data", "artifacts").replace('\\', '/')
    figures_dir = os.path.join(project_root, "reports", "figures").replace('\\', '/')
    
    model_output_path = os.path.join(artifacts_dir, "best_model.pkl").replace('\\', '/')
    metrics_output_path = os.path.join(artifacts_dir, "model_metrics.json").replace('\\', '/')
    confusion_matrix_path = os.path.join(figures_dir, "confusion_matrix.png").replace('\\', '/')
    
    target_var = state.get("target_variable", "target")
    preset = state.get("active_preset", "ENTERPRISE_STANDARD")
    
    # 1. Extract the metadata generated by the Pre-Flight Profiler
    dataset_metadata = state.get("dataset_metadata", {})
    num_rows = dataset_metadata.get("rows", 0)
    num_cols = dataset_metadata.get("cols", 0)

    system_prompt = f"""You are an expert Machine Learning Modelling Agent.
Your task is to write Python code to train, evaluate and persist machine learning models using the engineered dataset located at '{input_path}'.
Perform the following operations exactly:

1. Load the dataset.
2. Separate predictors (X) and target variable (y = df['{target_var}']).
3. If the target variable is object/string type, encode it using `LabelEncoder`.
4. Convert boolean predictor columns to floats.
5. Split the data into training and testing sets using an 80/20 split with `random_state=42`.
6. Train models according to your Persona Rules.
7. Select the single best model strictly according to F1-score.
8. Save the best model using `joblib.dump()` to:
   '{model_output_path}'.
9. Save a JSON file to '{metrics_output_path}' containing:
   - model_name
   - selected_preset: {preset}
   - accuracy
   - precision
   - recall
   - f1_score
   - model_training_time (this should be the total time taken to train all models, not just the best one)
10. Generate a Confusion Matrix for the selected model and save it to:
   '{confusion_matrix_path}'.

CRITICAL RULES:
- Output ONLY valid Python code.
- Never wrap code in markdown.
- Never output explanations.
- Create output directories using `os.makedirs(..., exist_ok=True)`.
- ALWAYS use `random_state=42` wherever supported.
- NEVER perform hyperparameter optimisation unless explicitly instructed by your Persona Rules.
- ALWAYS use F1-score as the model selection criterion.
- If multiple models are trained, discard all non-selected models after evaluation and persist ONLY the best model.
- Save plots using `plt.savefig(..., bbox_inches='tight')` followed immediately by `plt.close()`.

--- DYNAMIC PERSONA INJECTION: {preset} ---
"""
    
    if preset == "RAPID_BASELINE":
        system_prompt += f"""
    MISSION:
    Produce a baseline predictive model in the shortest possible time.

    PERSONA RULES:
    - Optimise purely for execution speed.
    - You MAY use Foundation Models.
    - Import `torch`.
    - Detect GPU availability using `torch.cuda.is_available()`.

    DATASET REALITY:
    - Rows: {num_rows}
    - Columns: {num_cols}

    MODEL POLICY:
    - If rows <= 10000 AND columns <= 500:
        Train ONLY a TabPFNClassifier.
        Use device='cuda' if available, otherwise 'cpu'.
        Use model = TabPFNClassifier(device=device)
    - Otherwise:
        Train ONLY a LogisticRegression(solver='liblinear', random_state=42).

    Never train multiple models.
    Never perform cross-validation.
    Never perform hyperparameter tuning.
    Evaluate immediately.
    """    
    
    elif preset == "QUICK_EXPLAINABLE":
        system_prompt += """
    MISSION:
    Produce a highly interpretable predictive model quickly.

    PERSONA RULES:
    - Train ONLY a DecisionTreeClassifier(max_depth=4, random_state=42).
    - Do not train LogisticRegression.
    - Do not train ensembles.
    - Do not train neural networks.
    - Do not tune hyperparameters.
    - Produce a model whose decision rules are easy to explain to non-technical stakeholders.
    """
    
    elif preset == "KAGGLE_COMPETITOR":
        system_prompt += """
    MISSION:
    Maximise predictive performance regardless of computation time.

    PERSONA RULES:
    - Train RandomForest, DecisionTreeClassifier, LogisticRegression, XGBClassifier and LGBMClassifier.
    - Optimise using RandomizedSearchCV (n_iter=5, random_state=42).
    - Select the best tuned model using F1-score.
    - Ignore interpretability completely.
    - Computational cost is not a concern.
    """    
    
    elif preset == "ENTERPRISE_STANDARD":
        system_prompt += """
    MISSION:
    Produce a reliable production-quality predictive model.

    PERSONA RULES:
    - Train a LogisticRegression(random_state=42).
    - Train a RandomForestClassifier(random_state=42).
    - Train an XGBClassifier(random_state=42).
    - Do not perform expensive hyperparameter optimisation.
    - Compare both models using default parameters.
    - Select the best model using F1-score.
    - Prefer robustness and maintainability over squeezing out marginal performance gains.
    """
        
    elif preset == "REGULATORY_COMPLIANCE":
        system_prompt += """
    MISSION:
    Produce a fully transparent and auditable predictive model.

    PERSONA RULES:
    - Train a LogisticRegression(random_state=42).
    - Train a DecisionTreeClassifier(max_depth=4, random_state=42).
    - Never train ensembles.
    - Never train boosting algorithms.
    - Never train neural networks.
    - Never tune hyperparameters.
    - Select the better model using F1-score.
    - Every learned parameter or decision rule must remain human-interpretable.
    """
        
    elif preset == "C_SUITE_PITCH":
        system_prompt += """
    MISSION:
    This preset should never reach the Modelling Agent.

    If this prompt has been invoked, simply generate the simplest possible
    LogisticRegression model so that execution can complete safely.

    Do not train multiple models.
    Do not tune hyperparameters.
    """

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content="Please write the Python code to train and evaluate the models now.")
    ]
    
    repl = DataScienceREPL()
    max_retries = 3
    attempts = 0

    # --- OBSERVABILITY: Local Accumulators ---
    node_input_tokens = 0
    node_output_tokens = 0
    node_timestamps = []
    
    # 3. Intra-Node Execution and Self-Correction Loop
    while attempts < max_retries:
        attempts += 1
        print(f"\n--- ATTEMPT {attempts}/{max_retries} ---")
        
        if attempts > 1:
            print("Cooling down for 15 seconds to respect API rate limits...")
            time.sleep(15)
            
        try:
            response = llm.invoke(messages)

            # --- OBSERVABILITY: Intercept Usage Metadata ---
            usage = response.usage_metadata or {}
            node_input_tokens += usage.get("input_tokens", 0)
            node_output_tokens += usage.get("output_tokens", 0)
            node_timestamps.append(time.time())
            
            # --- SAFELY EXTRACT CONTENT (Handles both Strings and Multimodal Lists) ---
            raw_content = response.content
            if isinstance(raw_content, list):
                # Extract the text from the list of blocks
                text_content = "".join(block.get("text", "") for block in raw_content if isinstance(block, dict))
            else:
                text_content = str(raw_content)
                
            # Sanitize the output: strip out markdown blocks
            generated_code = text_content.replace("```python", "").replace("```", "").strip()
            print("Generated Code:\n", generated_code)
            
            # Execute the code
            execution_result = repl.execute_code(generated_code)
            
            # 4. Evaluate and Update State
            if execution_result["success"]:
                print("Status: Success")
                
                artifacts = state.get("artifacts", {})
                artifacts["best_model"] = model_output_path
                artifacts["model_metrics"] = metrics_output_path
                artifacts["confusion_matrix"] = confusion_matrix_path
                
                return {
                    "artifacts": artifacts,
                    "messages": [f"Modelling Agent successfully trained and saved models after {attempts} attempt(s)."],
                    "error_flag": False,
                    "current_step": "modelling",
                    # Pass accumulated tokens and timestamps to the LangGraph state
                    "total_input_tokens": state.get("total_input_tokens", 0) + node_input_tokens,
                    "total_output_tokens": state.get("total_output_tokens", 0) + node_output_tokens,
                    "api_call_timestamps": node_timestamps
                }
            else:
                error_msg = execution_result['output']
                print(f"Status: Failed - {error_msg}")
                
                correction_prompt = f"""The code failed with the following error:
{error_msg}

Please fix the code and provide the complete, corrected script. Ensure you import all necessary metrics from sklearn.metrics and handle file saving correctly."""
                messages.append(HumanMessage(content=correction_prompt))
                
        except Exception as e:
            error_str = str(e)
            if "429" in error_str or "RESOURCE_EXHAUSTED" in error_str:
                print(f"⚠️ API Rate Limit Hit! Forcing a 65-second deep cooldown...")
                time.sleep(65.0)  # <-- INCREASE THIS TO 65
                # Note: Because this is a failed run, you don't need to track this 
                # sleep time for the final ablation study baseline. You only track 
                # the time of a fully successful, uninterrupted run.
            else:
                print(f"⚠️ API Error encountered: {error_str}")
                time.sleep(5.0) # Standard small delay for non-quota errors

    print("\nStatus: Max retries reached. Node failed.")
    return {
        "error_flag": True,
        "error_message": "Modelling Agent failed.",
        "total_input_tokens": state.get("total_input_tokens", 0) + node_input_tokens,
        "total_output_tokens": state.get("total_output_tokens", 0) + node_output_tokens,
        "api_call_timestamps": node_timestamps
    }